repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
        exclude: deploy/helm
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
        exclude: components/automate-app/migrations/
      - id: end-of-file-fixer
        exclude: components/automate-app/migrations/|components/automate-app/tests/assets

  - repo: https://github.com/Jarmos-san/shellcheck-precommit
    rev: 'v0.2.0'
    hooks:
      - id: shellcheck-system
        name: shellcheck

  - repo: local
    hooks:
      - id: lockfilelint
        name: lockfilelint
        entry: yarn precommit:lockfilelint
        pass_filenames: false
        types: [file]
        language: system
      # this is effectively the same as `yarn run all`, but each step is separated so we can more easily identify which step failed
      - id: prettier
        name: prettier
        entry: yarn precommit:prettier
        pass_filenames: true
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue, css]
        language: system

      - id: tsclint
        name: Typescript linting
        entry: yarn lint:tsc
        pass_filenames: false
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        language: system

      - id: eslint
        name: eslint
        entry: yarn precommit:eslint
        pass_filenames: true
        language: system
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        exclude: .yarn

      - id: drizzle
        name: drizzle
        entry: yarn db:generate
        pass_filenames: false
        language: system
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        exclude: .yarn

  - repo: https://github.com/specklesystems/pre-commit
    rev: '0.2.0'
    hooks:
      - id: ggshield-not-ci
        name: ggshield

  - repo: https://github.com/syntaqx/git-hooks
    rev: 'v0.0.17'
    hooks:
      - id: circleci-config-validate
